### PR TITLE
小细节

### PR DESCRIPTION
**Pull request by hejiehao**

### CODE REVIEW

**Comment by Seayay** [comment]
https://github.com/GlobeMC/crashmc.com/commit/faa2a00503beba8369089026ca971462ab9f9888 重复提交

**Comment by hejiehao** [comment]
> [faa2a00](https://github.com/GlobeMC/crashmc.com/commit/faa2a00503beba8369089026ca971462ab9f9888) 重复提交

你仔细看看

**Comment by Seayay** [comment]
> > [faa2a00](https://github.com/GlobeMC/crashmc.com/commit/faa2a00503beba8369089026ca971462ab9f9888) 重复提交
> 
> 你仔细看看

https://github.com/GlobeMC/crashmc.com/commit/cc71500ba60b3b889d5dca6465f7ed3f10771049

**Comment by hejiehao** [comment]
> > > [faa2a00](https://github.com/GlobeMC/crashmc.com/commit/faa2a00503beba8369089026ca971462ab9f9888) 重复提交
> > 
> > 
> > 你仔细看看
> 
> [cc71500](https://github.com/GlobeMC/crashmc.com/commit/cc71500ba60b3b889d5dca6465f7ed3f10771049)

你再仔细看看

**Comment by Seayay** [comment]
> > > > [faa2a00](https://github.com/GlobeMC/crashmc.com/commit/faa2a00503beba8369089026ca971462ab9f9888) 重复提交
> > > 
> > > 
> > > 你仔细看看
> > 
> > 
> > [cc71500](https://github.com/GlobeMC/crashmc.com/commit/cc71500ba60b3b889d5dca6465f7ed3f10771049)
> 
> 你再仔细看看

https://github.com/GlobeMC/crashmc.com/commit/23785a704feb2937e3829a192e8c68552a96178d

**Pull request closed without merging**
